"Unknown option: regular" when creating a new website root
terminal42/contao-folderpage pull request #22
Opened 2022-01-10 10:49 UTC by fritzmg

See https://github.com/contao/contao/issues/3901

This is still caused by the `onload_callback` (see also https://github.com/terminal42/contao-folderpage/issues/21).

What is the purpose of `Terminal42\FolderpageBundle\DataContainer::setRootType`, i.e. what problem does it attempt to resolve? Removing that custom callback completely would resolve both issues and I do not notice any other issues.

2022-01-10 14:45 UTC, aschempp requested changes
I don't think this can be removed. By default in Contao, the first page in the tree must be a root page. With `folderpage` though, that can also be a folder to group multiple roots. But the first page in a root folder must be a root page then. I think that would be lost if you drop this method.

2022-01-10 15:00 UTC, fritzmg commented
> With folderpage though, that can also be a folder to group multiple roots. But the first page in a root folder must be a root page then. I think that would be lost if you drop this method.

I cannot create a folder at root level in the current state of this extension. So this does not seem to work as intended in any case.

2022-01-11 09:11 UTC, fritzmg commented
How do you want to procede here? As it stands this feature is not actually implemented. I also noticed that there is a `Page::getPageTypes` function which presumably allows to create website roots within folders - but it's not actually used anywhere.

I am also not sure it really makes sense to allow folders on the root level? I.e. doesn't that open a can of worms potentially? 😁

2022-01-21 09:02 UTC, aschempp commented
Idk really, I use that feature on multiple installations, so it must be there 😂
did you check this in Contao 4.9 and 4.13 ?

2022-01-21 09:13 UTC, fritzmg commented
In Contao 4.9 the following error happens when `terminal42/contao-folderpage` is installed when you try to create a new website root:

```
Symfony\Component\Routing\Exception\InvalidParameterException:
Parameter "_locale" for route "contao_frontend" must match "[a-z]{2}(?:\-[A-Z]{2})?" ("" given) to generate a corresponding URL.

  at vendor\symfony\routing\Generator\UrlGenerator.php:193
  at Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(array('_locale' => 0, 'alias' => 1), array('_token_check' => true, '_controller' => 'Contao\\CoreBundle\\Controller\\FrontendController::indexAction', '_scope' => 'frontend'), array('alias' => '.+', '_locale' => '[a-z]{2}(\\-[A-Z]{2})?'), array(array('variable', '/', '.+', 'alias'), array('variable', '/', '[a-z]{2}(?:\\-[A-Z]{2})?', '_locale')), array('_locale' => null, 'alias' => 'ee25dd1302abe25996f5'), 'contao_frontend', 0, array())
     (vendor\symfony-cmf\routing\src\ProviderBasedGenerator.php:78)
  at Symfony\Cmf\Component\Routing\ProviderBasedGenerator->generate('contao_frontend', array('_locale' => null, 'alias' => 'ee25dd1302abe25996f5'), 0)
     (vendor\symfony-cmf\routing\src\DynamicRouter.php:180)
  at Symfony\Cmf\Component\Routing\DynamicRouter->generate('contao_frontend', array('_locale' => null, 'alias' => 'ee25dd1302abe25996f5'), 0)
     (vendor\symfony-cmf\routing\src\ChainRouter.php:248)
  at Symfony\Cmf\Component\Routing\ChainRouter->generate('contao_frontend', array('_locale' => null, 'alias' => 'ee25dd1302abe25996f5'), 0)
     (vendor\contao\contao\core-bundle\src\Routing\UrlGenerator.php:81)
  at Contao\CoreBundle\Routing\UrlGenerator->generate('ee25dd1302abe25996f5', array('_locale' => null, 'alias' => 'ee25dd1302abe25996f5'), 0)
     (vendor\contao\contao\core-bundle\src\Resources\contao\models\PageModel.php:1134)
  at Contao\PageModel->getAbsoluteUrl()
     (vendor\contao\contao\core-bundle\src\Resources\contao\dca\tl_page.php:996)
  at tl_page->getSerpUrl(object(PageModel))
     (vendor\contao\contao\core-bundle\src\Resources\contao\widgets\SerpPreview.php:150)
  at Contao\SerpPreview->getUrl(object(PageModel))
     (vendor\contao\contao\core-bundle\src\Resources\contao\widgets\SerpPreview.php:47)
  at Contao\SerpPreview->generate()
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Widget.php:651)
  at Contao\Widget->generateWithError(true)
     (vendor\contao\contao\core-bundle\src\Resources\contao\templates\backend\be_widget.html5:3)
  at include('vendor\\contao\\contao\\core-bundle\\src\\Resources\\contao\\templates\\backend\\be_widget.html5')
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\TemplateInheritance.php:100)
  at Contao\Widget->inherit()
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Widget.php:598)
  at Contao\Widget->parse()
     (vendor\contao\contao\core-bundle\src\Resources\contao\classes\DataContainer.php:668)
  at Contao\DataContainer->row('{title_legend},title,alias,type;{language_legend:hide},languageMain,languageQuery;{meta_legend},pageTitle,robots,description,serpPreview;{protected_legend:hide},protected;{layout_legend:hide},includeLayout;{cache_legend:hide},includeCache;{chmod_legend:hide},includeChmod;{expert_legend:hide},cssClass,sitemap,hide,noSearch,guests,requireItem;{tabnav_legend:hide},tabindex,accesskey;{publish_legend},published,start,stop')
     (vendor\contao\contao\core-bundle\src\Resources\contao\drivers\DC_Table.php:1979)
  at Contao\DC_Table->edit()
     (vendor\contao\contao\core-bundle\src\Resources\contao\classes\Backend.php:644)
  at Contao\Backend->getBackendModule('page', null)
     (vendor\contao\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:162)
  at Contao\BackendMain->run()
     (vendor\contao\contao\core-bundle\src\Controller\BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor\symfony\http-kernel\HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\http-kernel\HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\index.php:31)
  at require('web\\index.php')
     (web\app.php:4)
```

2022-01-21 09:31 UTC, fritzmg commented
And if I temporarily add `return '';` to `tl_page::getSerpUrl` in Contao 4.9, I can add folder pages add root level - however I can add _all_ page types at root level, which is also not correct.

2022-05-19 07:15 UTC, aschempp commented
This should be fixed in 2.0.16 (d3cec08283c8aefe7805810db956b4905bfd99d3)

2022-05-19 07:15 UTC, closed without merging